version: "3.8"

services:
  token_vault_db:
    image: postgres:15-alpine
    container_name: token_vault_postgres

    environment:
      POSTGRES_USER: ${TOKEN_DB_USER}
      POSTGRES_PASSWORD: ${TOKEN_DB_PASSWORD}
      POSTGRES_DB: ${TOKEN_DB_NAME}
    ports:
      - "${TOKEN_DB_PORT}:5432"
    volumes:
      - ./token-db-data:/var/lib/postgresql/data

    restart: always

  token_api:
    build: .
    container_name: token_vault_api

    environment:
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      PORT: 3005

      DATABASE_URL: postgresql://${TOKEN_DB_USER}:${TOKEN_DB_PASSWORD}@token_vault_db:5432/${TOKEN_DB_NAME}
    ports:
      - "3005:3005"
    depends_on:
      - token_vault_db
    restart: always
